version: '3.9'
services:
  request-logs-service:
    build: .
    env_file: .env
    ports:
      - "6000:6000"
    depends_on:
      - postgres
      - mongo
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: request_logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata:
